[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
]
anvil = "http://localhost:8545"
[rpc_endpoints]
SEPOLIA_RPC_URL = "https://eth-sepolia.g.alchemy.com/v2/RxXZAAx0s3Jt9gHNs_2h1"
ETHERSCAN_API_KEY = "PNXI9TJY9T95E95WYVCQFDMYE7GNV7IEKN"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
